repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts

releases:
  - name: promtail
    namespace: monitoring
    createNamespace: true 
    chart: grafana/promtail
    version: 6.16.4
    values:
    - values.yaml