apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-metrics-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: default
  # Sources field specifies the list of sources for the application
  sources:
  - chart: metrics-server
    repoURL: https://kubernetes-sigs.github.io/metrics-server
    targetRevision: "3.11.0"
    helm:
      version: v3
      releaseName: metrics-server
      valueFiles:
      - $values-repo/cluster1/monitoring/kubernetes-metrics-server/values.yaml
  - repoURL: https://github.com/mochizuki875/ClusterSetup
    targetRevision: main
    ref: values-repo
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
    syncOptions:     # Sync options which modifies sync behavior
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: ""
    kind: Service
    jsonPointers:
    - /spec/clusterIP