repositories:
- name: jetstack
  url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true 
    chart: jetstack/cert-manager
    version: 1.13.3
    values:
    - values.yaml