apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  project: default
  # Sources field specifies the list of sources for the application
  sources:
  - chart: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "2.9.11"
    helm:
      version: v3
      releaseName: loki-stack
      valueFiles:
      - $values-repo/cluster1/monitoring/loki-stack/values.yaml
  - repoURL: https://github.com/mochizuki875/ClusterSetup
    targetRevision: main
    ref: values-repo
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:     # Sync options which modifies sync behavior
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: ""
    kind: Service
    jsonPointers:
    - /spec/clusterIP