loki:
  enabled: true
  isDefault: false
  datasource: {}
    # jsonData: {}
    # uid: ""
  nodeSelector: 
    dedicated: monitoring
  tolerations:
  - key: "dedicated"
    value: "monitoring"
    operator: "Equal"
    effect: "NoSchedule"

grafana:
  enabled: false
  sidecar:
    datasources:
      enabled: false # GrafanaのDataSource For SideCarで拾うConfigMapを作成しない
      maxLines: 1000