apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: monitoring-bucket
# Change "rook-ceph" provisioner prefix to match the operator namespace if needed
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Delete
parameters:
  objectStoreName: monitoring-cos
  objectStoreNamespace: rook-ceph