apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: instrumentation
  namespace: default
spec:
  exporter:
    endpoint: http://opentelemetry-collector.monitoring.svc:4317
  propagators:
    - tracecontext
    - baggage
    - b3