kind: ConfigMap
metadata:
  name: grafana-agent-traces
  namespace: monitoring
apiVersion: v1
data:
  agent.yaml: |
    tempo:
        configs:
          - batch:
                send_batch_size: 1000
                timeout: 5s
            name: default
            receivers:
                otlp:
                    protocols:
                        grpc: null
                        http: null
            remote_write:
              # - endpoint: tempo:4317
              - endpoint: tempo-tempo-distributed-distributor:4317
                insecure: true
                retry_on_failure:
                    enabled: false
            # Span Metrics Processor有効化
            # spanmetrics:
            #   latency_histogram_buckets: [2ms, 4ms, 6ms, 8ms, 10ms, 50ms, 100ms, 200ms, 400ms, 800ms, 1s, 1400ms, 2s, 5s, 10s, 15s]
            #   dimensions:
            #     - name: http.method
            #       default: GET
            #     - name: http.status_code
            #     - name: traceID # 付けてみたけどラベルに含まれない
            #     - name: spanID
            #   const_labels: 
            #     metrics_exporter: otlp/spanmetrics
            #   handler_endpoint: 0.0.0.0:8889
            scrape_configs:
              - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
                job_name: kubernetes-pods
                kubernetes_sd_configs:
                  - role: pod
                relabel_configs:
                  - action: replace
                    source_labels:
                      - __meta_kubernetes_namespace
                    target_label: namespace
                  - action: replace
                    source_labels:
                      - __meta_kubernetes_pod_name
                    target_label: pod
                  - action: replace
                    source_labels:
                      - __meta_kubernetes_pod_container_name
                    target_label: container
                tls_config:
                    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                    insecure_skip_verify: true  
  strategies.json: '{"default_strategy": {"param": 1.0, "type": "probabilistic"}}'