repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts

releases:
  - name: tempo
    namespace: monitoring
    createNamespace: true 
    chart: grafana/tempo
    version: 1.7.1
    values:
    - values-single.yaml