apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    chart: ingress-nginx/ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    helm:
      releaseName: ingress-nginx
      valueFiles:
      - https://raw.githubusercontent.com/user/sample/values-nginx.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  # syncPolicy:
  #   automated:
  #     prune: true